2025-05-16T15:16:51.680622+0200 INFO Wird geloggt, da Filter passt
2025-05-16T15:16:51.681181+0200 ERROR An error has been caught in function '<module>', process 'MainProcess' (1348), thread 'MainThread' (9120):
Traceback (most recent call last):

> File "c:\Users\plix\stuff\kurse\python-intensiv\16_thirdparty\code\3_loguru.py", line 52, in <module>
    div_by_zero()  # auskommentiert für Sicherheit
    └ <function div_by_zero at 0x0000019A7E0E96C0>

  File "c:\Users\plix\stuff\kurse\python-intensiv\16_thirdparty\code\3_loguru.py", line 49, in div_by_zero
    1 / 0

ZeroDivisionError: division by zero
2025-05-16T15:18:45.259292+0200 INFO Wird geloggt, da Filter passt
2025-05-16T15:18:45.259810+0200 ERROR An error has been caught in function '<module>', process 'MainProcess' (17332), thread 'MainThread' (16500):
Traceback (most recent call last):

> File "c:\Users\plix\stuff\kurse\python-intensiv\16_thirdparty\code\3_loguru.py", line 55, in <module>
    div_by_zero()  # auskommentiert für Sicherheit
    └ <function div_by_zero at 0x0000027CB06396C0>

  File "c:\Users\plix\stuff\kurse\python-intensiv\16_thirdparty\code\3_loguru.py", line 52, in div_by_zero
    1 / 0

ZeroDivisionError: division by zero
2025-05-16T15:19:27.061100+0200 INFO Wird geloggt, da Filter passt
2025-05-16T15:19:27.061428+0200 ERROR An error has been caught in function '<module>', process 'MainProcess' (8144), thread 'MainThread' (16580):
Traceback (most recent call last):

> File "c:\Users\plix\stuff\kurse\python-intensiv\16_thirdparty\code\3_loguru.py", line 57, in <module>
    div_by_zero()  # auskommentiert für Sicherheit
    └ <function div_by_zero at 0x000001C048106480>

  File "c:\Users\plix\stuff\kurse\python-intensiv\16_thirdparty\code\3_loguru.py", line 54, in div_by_zero
    1 / 0

ZeroDivisionError: division by zero
2025-05-16T15:20:28.270735+0200 INFO Wird geloggt, da Filter passt
2025-05-16T15:20:28.270993+0200 ERROR An error has been caught in function '<module>', process 'MainProcess' (15140), thread 'MainThread' (10924):
Traceback (most recent call last):

> File "c:\Users\plix\stuff\kurse\python-intensiv\16_thirdparty\code\3_loguru.py", line 57, in <module>
    div_by_zero()  # auskommentiert für Sicherheit
    └ <function div_by_zero at 0x00000167D5306480>

  File "c:\Users\plix\stuff\kurse\python-intensiv\16_thirdparty\code\3_loguru.py", line 54, in div_by_zero
    1 / 0

ZeroDivisionError: division by zero
2025-05-16T15:21:23.446281+0200 INFO Wird geloggt, da Filter passt
2025-05-16T15:21:23.446519+0200 ERROR An error has been caught in function '<module>', process 'MainProcess' (15604), thread 'MainThread' (9040):
Traceback (most recent call last):

> File "c:\Users\plix\stuff\kurse\python-intensiv\16_thirdparty\code\3_loguru.py", line 57, in <module>
    div_by_zero()  # auskommentiert für Sicherheit
    └ <function div_by_zero at 0x000001D033C16480>

  File "c:\Users\plix\stuff\kurse\python-intensiv\16_thirdparty\code\3_loguru.py", line 54, in div_by_zero
    1 / 0

ZeroDivisionError: division by zero
